Repository Real-Estate-App-Team/RealEstateApp_Frontend, pull requests merged in 2023-11, with the labels that each got.

#1 home slider commit
  src/components/home-page/home-slider.jsx
Labels: Review Request

#2 git new commit
  src/components/home-page/home-slider.jsx
Labels: Review Request

#3 contact page changes
  src/components/home-page/home-slider.jsx
Labels: WIP

#4 contact page created
  src/pages/Contact.jsx
Labels: Review Request

#8 Navbar added and imgs added
  package-lock.json
  package.json
  public/assets/img/401.png
  public/assets/img/404.png
  public/assets/img/banner.png
  public/assets/img/favicon.png
  public/assets/img/highlight.png
  public/assets/img/logo-192.png
  public/assets/img/logo-512.png
  public/assets/img/logo-white-2.png
  public/assets/img/logo-white.png
  public/assets/img/logo.png
  src/components/common/navbar.jsx
  src/layouts/user-layout.jsx
Labels: Ready to Merge

#10 örnek commit
  .gitignore
  README.md
  package-lock.json
  package.json
  public/assets/img/401.png
  public/assets/img/404.png
  public/assets/img/banner.png
  public/assets/img/favicon.png
  public/assets/img/highlight.png
  public/assets/img/logo-192.png
  public/assets/img/logo-512.png
  public/assets/img/logo-white-2.png
  public/assets/img/logo-white.png
  public/assets/img/logo.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/components/common/footer.jsx
  src/components/common/footer.scss
  src/components/common/navbar.jsx
  src/components/common/spacer.jsx
  src/components/home-page/home-slider.jsx
  src/index.js
  src/layouts/user-layout.jsx
  src/pages/Contact.jsx
  src/pages/Home.jsx
  src/pages/errors/error-401.jsx
  src/router/router.js
  src/style/_mixins.scss
  src/style/_variables.scss
  src/style/index.scss
Labels: Ready to Merge
